name = "AlphaRAR"
defaultTargets = ["AlphaRAR"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "LeanMachineLearning"
git = "https://github.com/LeanMachineLearning/LML"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "AlphaRAR"
