import ChallengeVendor_Algorithm
import ChallengeVendor_StationaryEnv
import ChallengeVendor_FiniteActions
import Mathlib.Probability.Process.Filtration
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Algebra.Order.Star.Real
import Mathlib.Analysis.Asymptotics.SpecificAsymptotics
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Topology.MetricSpace.Pseudo.Lemmas
import Mathlib.Algebra.Ring.IsFormallyReal
import Mathlib.Topology.Separation.CompletelyRegular
import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
import Mathlib.MeasureTheory.Measure.Tight
import Mathlib.MeasureTheory.Order.Group.Lattice
import Mathlib.Probability.Martingale.Centering
import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.Probability.Moments.Variance
import Mathlib.Analysis.PSeries
import Mathlib.Probability.Martingale.Convergence
import Mathlib.Algebra.BigOperators.Module
import Mathlib.Analysis.Normed.Group.Continuity
import Mathlib.Analysis.Normed.Ring.Basic
import Mathlib.Order.Filter.AtTopBot.Archimedean
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Order.CompletePartialOrder
import Mathlib.Probability.Martingale.OptionalStopping
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.Calculus.FDeriv.Basic
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Analysis.SumIntegralComparisons
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.StrongLaw
import Mathlib.Data.Nat.Nth
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Distributions.Gaussian.Fernique
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondJensen
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
import Mathlib.MeasureTheory.Measure.LevyConvergence
import Mathlib.Probability.CondVar
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
import Mathlib.MeasureTheory.Measure.Portmanteau
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.MeasureTheory.Integral.Layercake
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals
import Mathlib.Data.Matrix.ColumnRowPartitioned
import Mathlib.Analysis.Calculus.ContDiff.Comp
import Mathlib.Analysis.Calculus.ContDiff.RCLike
import Mathlib.Analysis.Calculus.LocalExtr.Basic
import Mathlib.Analysis.Calculus.MeanValue

/-! # Standalone extraction for `AlphaRAR.aRTSFE_sparse_rate_of_isARTSFE`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee; the LML imports are replaced by the `ChallengeVendor_*` modules so the
import closure bottoms out in Mathlib.

`AlphaRAR.aRTSFE_sparse_rate_of_isARTSFE` is blueprint `thm:sparse_rate` stated from the
history-level design predicate `IsARTSFE`; `AlphaRAR.aRTSFE_sparse_rate` is the same conclusion
from the raw process-level throttle and forced-exploration hypotheses (which mention the history
filtration, whose auxiliary constants cannot be restated faithfully outside LML). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace ProbabilityTheory.Kernel
end ProbabilityTheory.Kernel
namespace AlphaRAR
end AlphaRAR

-- ═══ LeanMachineLearning.ArmIndicator ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace Learning
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {P : Measure Ω}

/-- The `{0,1}`-valued assignment indicator of arm `k`: `armIndicator A k n ω = 𝟙{A n ω = k}`. -/
noncomputable def armIndicator (A : ℕ → Ω → 𝓐) (k : 𝓐) (n : ℕ) (ω : Ω) : ℝ :=
  Set.indicator {ω | A n ω = k} (fun _ ↦ (1 : ℝ)) ω

end Learning
end

-- ═══ LeanMachineLearning.Means ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace ProbabilityTheory.Kernel
variable {𝓐 𝓨 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} [NormedAddCommGroup 𝓨] [NormedSpace ℝ 𝓨]

/-- The means of a kernel. -/
noncomputable def means (ν : Kernel 𝓐 𝓨) (k : 𝓐) : 𝓨 := (ν k)[id]

end ProbabilityTheory.Kernel
end

-- ═══ YDK2026.Count ═══
section
open Filter Finset MeasureTheory Learning
namespace AlphaRAR

/-- Allocation count of a fixed arm, `N n = ∑_{j<n} X j` (blueprint `def:counts`). Stated for a
general `AddCommMonoid` so it serves both the deterministic per-path counts (`X : ℕ → ℝ`) and the
process-level count (`X : ℕ → Ω → ℝ`, the assignment count process of `Assignment.lean`). -/
def count {M : Type*} [AddCommMonoid M] (X : ℕ → M) (n : ℕ) : M := ∑ j ∈ range n, X j

end AlphaRAR
end

-- ═══ YDK2026.Deterministic ═══
section
open Finset Filter
open scoped Topology
namespace AlphaRAR
variable (X p ρ : ℕ → ℝ) (α : ℝ)

/-- Sequential estimator of a fixed arm (blueprint `def:estimator`),
`θ̂ n = (∑_{j<n} X j ξ j + θ₀) / (N n + 1)`, with initial value `θ₀` and the `+1`
regularization in the denominator. -/
noncomputable def estimator (ξ : ℕ → ℝ) (θ₀ : ℝ) (n : ℕ) : ℝ :=
  ((∑ j ∈ range n, X j * ξ j) + θ₀) / (count X n + 1)

end AlphaRAR
end

-- ═══ YDK2026.ARTSAlgorithm ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Finset
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- History-level plug-in target `ρ̂_k`: the target map `T` applied to the vector of regularized
empirical means `(sumRewards' + θ₀)/(pullCount' + 1)` computed from a history `h : Iic n → 𝓐 × ℝ`.
This is the design's target as a function of the observed history, matching `aRTSTarget` on the
history of the process (`histTarget_eq`). -/
noncomputable def histTarget (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (k : 𝓐) (n : ℕ)
    (h : Iic n → 𝓐 × ℝ) : ℝ :=
  T (fun k' ↦ (sumRewards' n h k' + θ₀ k') / ((pullCount' n h k' : ℝ) + 1)) k

end AlphaRAR
end

-- ═══ YDK2026.ForcedExploration ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Real
open scoped Topology ENNReal NNReal Matrix
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- An **exploration schedule** (blueprint `def:exploration_schedule`, in the weakened form): a
nondecreasing threshold `h(m)` with `h(m) → ∞` and `h(m) = o(m)`. Monotonicity is a harmless
convenience that lets `h(ℓ) ≤ h(n)` for `ℓ ≤ n`.

The paper additionally requires `h(m) = o(√m)`; that is `IsSqrtSmall` below, deliberately *not* a
field here. It is needed only by the `√n`-scaled normality results, and even there it is not
necessary (`underExplored_eventually_empty`: under Condition **B** forced exploration switches
itself off, so any `h(m) = o(m)` does). Keeping it separate is what makes schedules with
`h(m) ≫ √m` available — and those are exactly the ones under which forced exploration, rather than
the data-dependent targeting rule, decides a *sparse* arm's sample size, which is what earns the
sparse componentwise CLT (`pullCount_div_sched_tendsto_one`, `aRTSFE_sparse_clt`). -/
structure IsExplorationSchedule (hsched : ℕ → ℝ) : Prop where
  /-- The schedule is nondecreasing. -/
  mono : Monotone hsched
  /-- The schedule diverges: `h(m) → ∞` (this is what forces every arm to be sampled infinitely
  often). -/
  tendsto_atTop : Tendsto hsched atTop atTop
  /-- The schedule is `o(m)`. -/
  div_tendsto_zero : Tendsto (fun m ↦ hsched m / (m : ℝ)) atTop (𝓝 0)

/-- **The forced-exploration aRTS design family** (blueprint `def:aRTSFE`, algorithm form) — the
`IsARTS` analogue for `aRTSFE`. An algorithm is an `α`-throttled forced-exploration aRTS design with
offsets `θ₀`, target map `T` and schedule `h` when its policy obeys two rules:

* **forced exploration takes priority**: if some arm is under-explored (`N_{n+1,j} ≤ h(n+1)`), then
  all of the policy's mass sits on the *least-sampled* under-explored arms — every other arm gets
  probability zero;
* **outside forced exploration the design is throttled**: an arm that is neither under-sampled nor
  under-explored gets probability at most `α ρ̂_k`.

Compared with `IsARTS`, the throttle carries the extra premise `h(n+1) < N_{n+1,k}`: forced
exploration is allowed to override it, which is exactly what the design is for.

Like `IsARTS`, this is stated purely on histories — no process, measure or filtration appears — so
it is a property of the algorithm alone, checkable design by design. `throttle_of_isARTSFE` and
`fe_of_isARTSFE` transport the two fields to the process-level hypotheses that the asymptotic
theorems consume. -/
structure IsARTSFE [DecidableEq 𝓐] (alg : Algorithm 𝓐 ℝ) (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ)
    (hsched : ℕ → ℝ) (α : ℝ) : Prop where
  /-- An arm that is neither under-sampled nor under-explored is throttled at `α ρ̂_k`. -/
  throttle : ∀ (n : ℕ) (hist : Finset.Iic n → 𝓐 × ℝ) (k : 𝓐),
    ((n : ℝ) + 1) * histTarget θ₀ T k n hist < (pullCount' n hist k : ℝ) →
      hsched (n + 1) < (pullCount' n hist k : ℝ) →
        (alg.policy n hist {k}).toReal ≤ α * histTarget θ₀ T k n hist
  /-- When some arm is under-explored, an arm that is not a least-sampled under-explored one cannot
  be drawn. -/
  forced : ∀ (n : ℕ) (hist : Finset.Iic n → 𝓐 × ℝ) (k : 𝓐),
    (∃ j, (pullCount' n hist j : ℝ) ≤ hsched (n + 1)) →
      (hsched (n + 1) < (pullCount' n hist k : ℝ) ∨
        ∃ j, (pullCount' n hist j : ℝ) ≤ hsched (n + 1) ∧
          (pullCount' n hist j : ℝ) < (pullCount' n hist k : ℝ)) →
        alg.policy n hist {k} = 0

/-- **Consistency and rate for sparse targets, from the design predicate** (blueprint
`thm:sparse_rate`). The `IsARTSFE` form of `aRTSFE_sparse_rate`: the process-level throttle and
forced-exploration hypotheses are discharged from the history-level design predicate through
`throttle_of_isARTSFE` and `fe_of_isARTSFE`, so — like the other headline results — the statement
mentions only the design, the environment and the schedule. -/
theorem aRTSFE_sparse_rate_of_isARTSFE [Fintype 𝓐] [DecidableEq 𝓐] [StandardBorelSpace 𝓐]
    [Nonempty 𝓐]
    (h : IsAlgEnvSeq A Y alg (stationaryEnv ν) P) (hνk : ∀ a, MemLp id 2 (ν a))
    (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (hT : Continuous T)
    (hTnn : ∀ z k, 0 ≤ T z k) (hTsum : ∀ z, ∑ k, T z k = 1)
    (α : ℝ) (hα : α ∈ Set.Icc (0 : ℝ) 1)
    {hsched : ℕ → ℝ} (hh : IsExplorationSchedule hsched)
    (hARTSFE : IsARTSFE alg θ₀ T hsched α) (k : 𝓐) :
    ∀ᵐ ω ∂P, Tendsto (fun n ↦ pullCount A k n ω) atTop atTop ∧
      Tendsto (fun n ↦ count (fun j ↦ armIndicator A k j ω) n / (n : ℝ))
        atTop (𝓝 (T ν.means k)) ∧
      ∃ C', ∀ᶠ n in atTop,
        |estimator (fun j ↦ armIndicator A k j ω) (Y · ω) (θ₀ k) n - ν.means k|
          ≤ C' * √(Real.log (Real.log (pullCount A k n ω : ℝ)) / (pullCount A k n ω : ℝ)) := sorry

end AlphaRAR
end
