import ChallengeVendor_Algorithm
import ChallengeVendor_StationaryEnv
import ChallengeVendor_FiniteActions
import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
import Mathlib.MeasureTheory.Measure.Tight
import Mathlib.MeasureTheory.Order.Group.Lattice
import Mathlib.Probability.Process.Filtration
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Algebra.Order.Star.Real
import Mathlib.Analysis.Asymptotics.SpecificAsymptotics
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Topology.MetricSpace.Pseudo.Lemmas
import Mathlib.Algebra.Ring.IsFormallyReal
import Mathlib.Topology.Separation.CompletelyRegular
import Mathlib.Probability.Martingale.Centering
import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.Probability.Moments.Variance
import Mathlib.Analysis.PSeries
import Mathlib.Probability.Martingale.Convergence
import Mathlib.Algebra.BigOperators.Module
import Mathlib.Analysis.Normed.Group.Continuity
import Mathlib.Analysis.Normed.Ring.Basic
import Mathlib.Order.Filter.AtTopBot.Archimedean
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Order.CompletePartialOrder
import Mathlib.Probability.Martingale.OptionalStopping
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Probability.Distributions.Gaussian.Fernique
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondJensen
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
import Mathlib.MeasureTheory.Measure.LevyConvergence
import Mathlib.Probability.CondVar
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
import Mathlib.MeasureTheory.Measure.Portmanteau
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.MeasureTheory.Integral.Layercake
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals

/-! # Standalone extraction for `AlphaRAR.aRTS_prop_dev`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee. -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace AlphaRAR
end AlphaRAR

-- ═══ LeanMachineLearning.ArmIndicator ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace Learning
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {P : Measure Ω}

/-- The `{0,1}`-valued assignment indicator of arm `k`: `armIndicator A k n ω = 𝟙{A n ω = k}`. -/
noncomputable def armIndicator (A : ℕ → Ω → 𝓐) (k : 𝓐) (n : ℕ) (ω : Ω) : ℝ :=
  Set.indicator {ω | A n ω = k} (fun _ ↦ (1 : ℝ)) ω

end Learning
end

-- ═══ Mathlib.StochasticOrder ═══
section
open MeasureTheory Filter Topology
open scoped ENNReal
namespace AlphaRAR
variable {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}

/-- `Y = o_p(1)`: the sequence `Y` converges to `0` in probability, i.e. in measure
(blueprint `def:op_Op`, order one). -/
def IsLittleOpOne (μ : Measure Ω) (Y : ℕ → Ω → ℝ) : Prop :=
  TendstoInMeasure μ Y atTop 0

end AlphaRAR
end

-- ═══ YDK2026.Count ═══
section
open Filter Finset MeasureTheory Learning
namespace AlphaRAR

/-- Allocation count of a fixed arm, `N n = ∑_{j<n} X j` (blueprint `def:counts`). Stated for a
general `AddCommMonoid` so it serves both the deterministic per-path counts (`X : ℕ → ℝ`) and the
process-level count (`X : ℕ → Ω → ℝ`, the assignment count process of `Assignment.lean`). -/
def count {M : Type*} [AddCommMonoid M] (X : ℕ → M) (n : ℕ) : M := ∑ j ∈ range n, X j

end AlphaRAR
end

-- ═══ YDK2026.Deterministic ═══
section
open Finset Filter
open scoped Topology
namespace AlphaRAR
variable (X p ρ : ℕ → ℝ) (α : ℝ)

/-- Sequential estimator of a fixed arm (blueprint `def:estimator`),
`θ̂ n = (∑_{j<n} X j ξ j + θ₀) / (N n + 1)`, with initial value `θ₀` and the `+1`
regularization in the denominator. -/
noncomputable def estimator (ξ : ℕ → ℝ) (θ₀ : ℝ) (n : ℕ) : ℝ :=
  ((∑ j ∈ range n, X j * ξ j) + θ₀) / (count X n + 1)

end AlphaRAR
end

-- ═══ YDK2026.ResponseConsistency ═══
section
open MeasureTheory ProbabilityTheory Filter Learning
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- **Attainable set of the estimator** (blueprint `def:attainable`, closure form). The closure of
all values `θ̂_{n,k}(ω)` of the sequential estimator for arm `k`, over times `n` and outcomes `ω`.
Every pointwise limit of `θ̂_{·,k}` lies in it (`estimator_limit_mem_attainableSet`), so Condition
**B**'s positivity requirement on this set transfers to the plug-in-target limit `u_k = T(z)_k`. -/
def attainableSet (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → ℝ) (θ₀ : ℝ) (k : 𝓐) : Set ℝ :=
  closure (Set.range fun p : ℕ × Ω ↦
    estimator (fun j ↦ armIndicator A k j p.2) (Y · p.2) θ₀ p.1)

end AlphaRAR
end

-- ═══ YDK2026.ARTSConsistency ═══
section
open MeasureTheory ProbabilityTheory Filter Learning
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- The aRTS plug-in target `ρ̂_{n,k} = T(θ̂_n)_k`: the continuous target map `T` applied to the
vector of sequential estimators of the arm means. -/
noncomputable def aRTSTarget (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → ℝ) (θ₀ : 𝓐 → ℝ)
    (T : (𝓐 → ℝ) → 𝓐 → ℝ) (n : ℕ) (ω : Ω) (k : 𝓐) : ℝ :=
  T (fun k' ↦ estimator (fun j ↦ armIndicator A k' j ω) (Y · ω) (θ₀ k') n) k

end AlphaRAR
end

-- ═══ YDK2026.ARTSAlgorithm ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Finset
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- History-level plug-in target `ρ̂_k`: the target map `T` applied to the vector of regularized
empirical means `(sumRewards' + θ₀)/(pullCount' + 1)` computed from a history `h : Iic n → 𝓐 × ℝ`.
This is the design's target as a function of the observed history, matching `aRTSTarget` on the
history of the process (`histTarget_eq`). -/
noncomputable def histTarget (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (k : 𝓐) (n : ℕ)
    (h : Iic n → 𝓐 × ℝ) : ℝ :=
  T (fun k' ↦ (sumRewards' n h k' + θ₀ k') / ((pullCount' n h k' : ℝ) + 1)) k

/-- **The aRTS design family** (blueprint `def:aRTS`, algorithm form). An algorithm `alg` is an
`α`-throttled aRTS design with offsets `θ₀` and target map `T` if its policy throttles every
over-sampled arm: for any history `h : Iic n → 𝓐 × ℝ`, if arm `k` is over-sampled
(`N_{n+1,k}(h) > (n+1) ρ̂_k(h)`), then the probability the policy assigns to arm `k` for the next
patient is at most `α ρ̂_k(h)`. -/
structure IsARTS (alg : Algorithm 𝓐 ℝ) (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (α : ℝ) : Prop where
  throttle : ∀ (n : ℕ) (h : Iic n → 𝓐 × ℝ) (k : 𝓐),
    ((n : ℝ) + 1) * histTarget θ₀ T k n h < (pullCount' n h k : ℝ) →
      (alg.policy n h {k}).toReal ≤ α * histTarget θ₀ T k n h

end AlphaRAR
end

-- ═══ YDK2026.PropDevARTS ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Finset
open scoped Topology ENNReal NNReal
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- **Deviation between proportions and plug-in target for the aRTS design**
(blueprint `lem:prop_dev`, `thm:normality` part (i), `o_p(√n)` half). For every arm `k`,
`|N_{n,k} - n ρ̂_{n,k}| = o_p(√n)`.

The `aRTS` instantiation of `prop_dev_of_hitting` at the last under-sampling time
`hitting (aRTSUnder …)`, fully self-contained: the `thm:LLN` consistencies `θ̂ → θ`
(`aRTS_theta_consistent`), `N/n → v` (`aRTS_proportion_tendsto`), the throttle
(`throttle_of_isARTS`, from the algorithm-level `IsARTS` predicate), and the smallness are all
discharged from the same
`aRTS_LLN` design bundle — an `IsAlgEnvSeq` sequence, `Y ∈ L²` (Condition **A**), a simplex-valued
`LipschitzWith K` target `T` (Condition **B**), `α ∈ [0,1)`, and the non-sparsity `hTpos`. The
smallness is automatic: at the last under-sampling time `N_ℓ - ℓ ρ̂_ℓ ≤ 0` (`preliminary_small`), so
`(1 + N_ℓ - ℓ ρ̂_ℓ)^+/√n ≤ 1/√n = o_p(1)`. The a.s. `O(√(n log log n))` bounds are a separate
statement. -/
lemma aRTS_prop_dev [Fintype 𝓐] [DecidableEq 𝓐] [StandardBorelSpace 𝓐] [Nonempty 𝓐]
    (h : IsAlgEnvSeq A Y alg (stationaryEnv ν) P) (hνk : ∀ a, MemLp id 2 (ν a))
    (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ)
    (hTnn : ∀ z k, 0 ≤ T z k) (hTsum : ∀ z, ∑ k, T z k = 1)
    (α : ℝ) (hα : α ∈ Set.Icc (0 : ℝ) 1) (hα1 : α < 1) (hARTS : IsARTS alg θ₀ T α)
    {K : ℝ≥0} (hlip : LipschitzWith K T)
    (hTpos : ∀ z : 𝓐 → ℝ, (∀ k, z k ∈ attainableSet A Y (θ₀ k) k) → ∀ k, 0 < T z k) (k : 𝓐) :
    IsLittleOpOne P (fun n ω ↦ ((pullCount A k n ω : ℝ)
      - (n : ℝ) * aRTSTarget A Y θ₀ T n ω k) / √n) := sorry

end AlphaRAR
end
