import Challenge_aRTS_clt_joint_Defs

/-! # Standalone extraction for `AlphaRAR.aRTS_clt_joint`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee. The shared definitions live in `Challenge_aRTS_clt_joint_Defs.lean`
(see there for why they are a separate module).

The measurability lemma `AlphaRAR.measurable_jointSqrtNVec` below is referenced by the *statement*
of the main theorem (through the `ProbabilityMeasure` subtype), so it is listed as a second
verification target in `aRTS_clt_joint.json` rather than proved here. -/

set_option quotPrecheck false

-- ═══ YDK2026.JointCLT ═══
section
open MeasureTheory Filter ProbabilityTheory Learning
open scoped Topology RealInnerProductSpace Matrix ENNReal
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] [Fintype 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- The `√n`-scaled proportion-deviation vector `√n(N_{n,k}/n - v_k) ∈ ℝ^𝓐`. -/
noncomputable def propSqrtNVec (A : ℕ → Ω → 𝓐) (v : 𝓐 → ℝ) (n : ℕ) (ω : Ω) : EuclideanSpace ℝ 𝓐 :=
  WithLp.toLp 2 (fun k ↦ √n * (count (fun j ↦ armIndicator A k j ω) n / (n : ℝ) - v k))

/-- The `√n`-scaled joint vector `(√n(N_n/n - v), √n(ρ̂_n - v)) ∈ ℝ^(𝓐 ⊕ 𝓐)`. -/
noncomputable def jointSqrtNVec (ν : Kernel 𝓐 ℝ) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → ℝ) (θ₀ : 𝓐 → ℝ)
    (T : (𝓐 → ℝ) → 𝓐 → ℝ) (v : 𝓐 → ℝ) (n : ℕ) (ω : Ω) : EuclideanSpace ℝ (𝓐 ⊕ 𝓐) :=
  WithLp.toLp 2 (Sum.elim (WithLp.ofLp (propSqrtNVec A v n ω))
    (WithLp.ofLp (targetSqrtNVec ν A Y θ₀ T n ω)))

omit [DecidableEq 𝓐] [Fintype 𝓐] in
lemma measurable_jointSqrtNVec [Finite 𝓐] (h : IsAlgEnvSeq A Y alg (stationaryEnv ν) P)
    (θ₀ : 𝓐 → ℝ) {T : (𝓐 → ℝ) → 𝓐 → ℝ} (hT : Continuous T) (v : 𝓐 → ℝ) (n : ℕ) :
    Measurable (jointSqrtNVec ν A Y θ₀ T v n) := sorry

end AlphaRAR
end

-- ═══ YDK2026.ARTSNormality ═══
section
open MeasureTheory ProbabilityTheory Filter Learning
open scoped Topology ENNReal NNReal Matrix
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- **Joint central limit theorem for the aRTS design** (blueprint `thm:normality` part (ii)),
fully self-contained. From the `aRTS` design bundle — an `IsAlgEnvSeq` sequence, Condition **A**
(`hY2` and the kernel `L²` bound `hνk`), a simplex-valued target `T` that is `LipschitzWith K`
(Condition **B**), the algorithm-level predicate `IsARTS`, `α ∈ [0,1)`, the non-sparsity `hTpos`,
and the first-order differentiability of `T` at `θ` with Jacobian `G` (`hTderiv`) — the `√n`-scaled
joint vector `(√n(N_n/n - v), √n(ρ̂_n - v))` converges weakly to the block-Gaussian `𝒩(0, Ω)`, with
every block equal to `G · diag(V_k / v_k) · Gᵀ` with `V_k = Var[id; ν k]`, and
`v_k = T ν.means k`.

The `aRTS` instantiation of `clt_joint_of_hitting` at the last under-sampling time: the throttle is
`throttle_of_isARTS` (from `IsARTS`), the consistency smallness is `generic_small_of_hitting`, and
the `o_p`-smallness is automatic (`N_ℓ - ℓ ρ̂_ℓ ≤ 0`, `preliminary_small`). -/
theorem aRTS_clt_joint [Fintype 𝓐] [DecidableEq 𝓐] [StandardBorelSpace 𝓐] [Nonempty 𝓐]
    (h : IsAlgEnvSeq A Y alg (stationaryEnv ν) P)
    (hνk : ∀ a, MemLp id 2 (ν a)) (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ)
    (hTnn : ∀ z k, 0 ≤ T z k) (hTsum : ∀ z, ∑ k, T z k = 1)
    (α : ℝ) (hα : α ∈ Set.Icc (0 : ℝ) 1) (hα1 : α < 1) (hARTS : IsARTS alg θ₀ T α)
    {K : ℝ≥0} (hlip : LipschitzWith K T)
    (hTpos : ∀ z : 𝓐 → ℝ, (∀ k, z k ∈ attainableSet A Y (θ₀ k) k) → ∀ k, 0 < T z k)
    (G : Matrix 𝓐 𝓐 ℝ)
    (hTderiv : HasFDerivAt
      (fun x : EuclideanSpace ℝ 𝓐 ↦ (WithLp.toLp 2 (T (WithLp.ofLp x)) : EuclideanSpace ℝ 𝓐))
      (Matrix.toEuclideanCLM (𝕜 := ℝ) G) (WithLp.toLp 2 ν.means)) :
    Tendsto (β := ProbabilityMeasure (EuclideanSpace ℝ (𝓐 ⊕ 𝓐)))
      (fun n : ℕ ↦ (⟨P.map (jointSqrtNVec ν A Y θ₀ T (T ν.means) n),
        Measure.isProbabilityMeasure_map
          (measurable_jointSqrtNVec h θ₀ hlip.continuous (T ν.means) n).aemeasurable⟩
          : ProbabilityMeasure (EuclideanSpace ℝ (𝓐 ⊕ 𝓐))))
      atTop
      (𝓝 ⟨multivariateGaussian 0 (Matrix.fromBlocks
        (G * Matrix.diagonal (fun a ↦ Var[id; ν a] / T ν.means a) * Gᵀ)
        (G * Matrix.diagonal (fun a ↦ Var[id; ν a] / T ν.means a) * Gᵀ)
        (G * Matrix.diagonal (fun a ↦ Var[id; ν a] / T ν.means a) * Gᵀ)
        (G * Matrix.diagonal (fun a ↦ Var[id; ν a] / T ν.means a) * Gᵀ)),
          inferInstance⟩) := sorry

end AlphaRAR
end
