import Mathlib.Probability.Process.Filtration
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Algebra.Order.Star.Real
import Mathlib.Analysis.Asymptotics.SpecificAsymptotics
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Topology.MetricSpace.Pseudo.Lemmas
import Mathlib.Algebra.Ring.IsFormallyReal
import Mathlib.Topology.Separation.CompletelyRegular
import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
import Mathlib.MeasureTheory.Measure.Tight
import Mathlib.MeasureTheory.Order.Group.Lattice
import Mathlib.Probability.Martingale.Centering
import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.Probability.Moments.Variance
import Mathlib.Analysis.PSeries
import Mathlib.Probability.Martingale.Convergence
import Mathlib.Algebra.BigOperators.Module
import Mathlib.Analysis.Normed.Group.Continuity
import Mathlib.Analysis.Normed.Ring.Basic
import Mathlib.Order.Filter.AtTopBot.Archimedean
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Order.CompletePartialOrder
import Mathlib.Probability.Martingale.OptionalStopping
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.Calculus.FDeriv.Basic
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Analysis.SumIntegralComparisons
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.StrongLaw
import Mathlib.Data.Nat.Nth
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.HasCondDistrib
import Mathlib.Probability.HasLaw
import Mathlib.Probability.Martingale.BorelCantelli

/-! # Standalone extraction for `AlphaRAR.aRTS_LLN`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee, with the LML declarations the statement rests on vendored in below,
so that this file is self-contained over Mathlib (its transitive imports resolve to Mathlib and
Lean core only, as the Palomar registry requires). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace ProbabilityTheory.Kernel
end ProbabilityTheory.Kernel
namespace AlphaRAR
end AlphaRAR

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Algorithm ═══
-- The declarations of https://github.com/LeanMachineLearning/LML that the statement rests on,
-- copied verbatim (Apache 2.0, Authors: Rémy Degenne, Paulo Rauber) so that this file's imports
-- bottom out in Mathlib. Comparator checks each constant is *identical* to the LML package's.
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓐 𝓨 Ω : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- A stochastic, sequential algorithm. -/
structure Algorithm (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] where
  /-- Policy or sampling rule: distribution of the next action. -/
  policy : (n : ℕ) → Kernel (Iic n → 𝓐 × 𝓨) 𝓐
  /-- The policy is a Markov kernel. -/
  [h_policy : ∀ n, IsMarkovKernel (policy n)]
  /-- Distribution of the first action. -/
  p0 : Measure 𝓐
  /-- The first action distribution is a probability measure. -/
  [hp0 : IsProbabilityMeasure p0]

instance (alg : Algorithm 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) := alg.h_policy n
instance (alg : Algorithm 𝓐 𝓨) : IsProbabilityMeasure alg.p0 := alg.hp0

/-- A stochastic environment. -/
structure Environment (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] where
  /-- Distribution of the next observation as function of the past history. -/
  feedback : (n : ℕ) → Kernel ((Iic n → 𝓐 × 𝓨) × 𝓐) 𝓨
  /-- The feedback kernels are Markov kernels. -/
  [h_feedback : ∀ n, IsMarkovKernel (feedback n)]
  /-- Distribution of the first observation given the first action. -/
  ν0 : Kernel 𝓐 𝓨
  /-- The initial observation kernel is a Markov kernel. -/
  [hp0 : IsMarkovKernel ν0]

instance (env : Environment 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) := env.h_feedback n
instance (env : Environment 𝓐 𝓨) : IsMarkovKernel env.ν0 := env.hp0

section IsAlgEnvSeq

variable {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence up to time `n`. -/
def history (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Iic n → 𝓐 × 𝓨 :=
  fun i ↦ (A i ω, Y i ω)

section IsAlgEnvSeq


/-- An algorithm-environment sequence: a sequence of actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The first action has the correct law. -/
  hasLaw_action_zero : HasLaw (fun ω ↦ (A 0 ω)) alg.p0 P
  /-- The first feedback has the correct conditional distribution. -/
  hasCondDistrib_feedback_zero : HasCondDistrib (Y 0) (A 0) env.ν0 P
  /-- The next action has the correct conditional distribution given the history. -/
  hasCondDistrib_action n :
    HasCondDistrib (A (n + 1)) (history A Y n) (alg.policy n) P
  /-- The next feedback has the correct conditional distribution given the history and
  next action. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y (n + 1)) (fun ω ↦ (history A Y n ω, A (n + 1) ω))
      (env.feedback n) P

end IsAlgEnvSeq

end IsAlgEnvSeq

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StationaryEnv ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓐 𝓨 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}

/-- An oblivious environment, in which the distribution of the next feedback depends only on
the last action, but in a possibly time-dependent manner. -/
@[simps]
def obliviousEnv (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment 𝓐 𝓨 where
  feedback n := (ν (n + 1)).prodMkLeft _
  ν0 := ν 0

/-- A stationary environment, in which the distribution of the next feedback depends only on the
last action. -/
def stationaryEnv (ν : Kernel 𝓐 𝓨) [IsMarkovKernel ν] : Environment 𝓐 𝓨 := obliviousEnv fun _ ↦ ν

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.FiniteActions ═══
section
open MeasureTheory Finset Learning
namespace Learning
variable {𝓐 R Ω : Type*} {m𝓐 : MeasurableSpace 𝓐} {mR : MeasurableSpace R} {mΩ : MeasurableSpace Ω}
  [DecidableEq 𝓐]
  {alg : Algorithm 𝓐 R} {env : Environment 𝓐 R}
  {P : Measure Ω} [IsProbabilityMeasure P]
  {A : ℕ → Ω → 𝓐} {R' : ℕ → Ω → R}
  {a : 𝓐} {m n t : ℕ} {ω : Ω}

/-- Number of times action `a` was chosen up to time `t` (excluding `t`). -/
noncomputable
def pullCount (A : ℕ → Ω → 𝓐) (a : 𝓐) (t : ℕ) (ω : Ω) : ℕ :=
  #(filter (fun s ↦ A s ω = a) (range t))

/-- Number of pulls of arm `a` up to (and including) time `n`.
This is the number of entries in `h` in which the arm is `a`. -/
noncomputable
def pullCount' (n : ℕ) (h : Iic n → 𝓐 × R) (a : 𝓐) := #{s | (h s).1 = a}

/-- Sum of rewards of arm `a` up to (and including) time `n`. -/
noncomputable
def sumRewards' (n : ℕ) (h : Iic n → 𝓐 × ℝ) (a : 𝓐) :=
  ∑ s, if (h s).1 = a then (h s).2 else 0

end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.ActionIndicator ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace Learning
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {P : Measure Ω}

/-- The `{0,1}`-valued assignment indicator of action `k`:
`actionIndicator A k n ω = 𝟙{A n ω = k}`. -/
noncomputable def actionIndicator (A : ℕ → Ω → 𝓐) (k : 𝓐) (n : ℕ) (ω : Ω) : ℝ :=
  {ω | A n ω = k}.indicator (fun _ ↦ (1 : ℝ)) ω

end Learning
end

-- ═══ LeanMachineLearning.Means ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace ProbabilityTheory.Kernel
variable {𝓐 𝓨 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} [NormedAddCommGroup 𝓨] [NormedSpace ℝ 𝓨]

/-- The means of a kernel. -/
noncomputable def means (ν : Kernel 𝓐 𝓨) (k : 𝓐) : 𝓨 := (ν k)[id]

end ProbabilityTheory.Kernel
end

-- ═══ YDK2026.Count ═══
section
open Filter Finset MeasureTheory Learning
namespace AlphaRAR

/-- Allocation count of a fixed arm, `N n = ∑_{j<n} X j`. Stated for a general `AddCommMonoid` so
it serves both the deterministic per-path counts (`X : ℕ → ℝ`) and the process-level count
(`X : ℕ → Ω → ℝ`, the assignment count process of `Assignment.lean`). -/
def count {M : Type*} [AddCommMonoid M] (X : ℕ → M) (n : ℕ) : M := ∑ j ∈ range n, X j

end AlphaRAR
end

-- ═══ YDK2026.Deterministic ═══
section
open Finset Filter
open scoped Topology
namespace AlphaRAR
variable (X p ρ : ℕ → ℝ) (α : ℝ)

/-- Sequential estimator of a fixed arm, equation (1) of the paper:
`θ̂ n = (∑_{j<n} X j ξ j + θ₀) / (N n + 1)`, with initial value `θ₀` and the `+1`
regularization in the denominator. -/
noncomputable def estimator (ξ : ℕ → ℝ) (θ₀ : ℝ) (n : ℕ) : ℝ :=
  ((∑ j ∈ range n, X j * ξ j) + θ₀) / (count X n + 1)

end AlphaRAR
end

-- ═══ YDK2026.ResponseConsistency ═══
section
open MeasureTheory ProbabilityTheory Filter Learning
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- **Attainable set of the estimator**, in closure form: the closure of all values `θ̂_{n,k}(ω)`
of the sequential estimator for arm `k`, over times `n` and outcomes `ω`. Every pointwise limit of
`θ̂_{·,k}` lies in it (`estimator_limit_mem_attainableSet`), so Condition **B**'s positivity
requirement on this set transfers to the plug-in-target limit `u_k = T(z)_k`. -/
def attainableSet (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → ℝ) (θ₀ : ℝ) (k : 𝓐) : Set ℝ :=
  closure (Set.range fun p : ℕ × Ω ↦
    estimator (fun j ↦ actionIndicator A k j p.2) (Y · p.2) θ₀ p.1)

end AlphaRAR
end

-- ═══ YDK2026.ARTSAlgorithm ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Finset
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- History-level plug-in target `ρ̂_k`: the target map `T` applied to the vector of regularized
empirical means `(sumRewards' + θ₀)/(pullCount' + 1)` computed from a history `h : Iic n → 𝓐 × ℝ`.
This is the design's target as a function of the observed history, matching `aRTSTarget` on the
history of the process (`histTarget_eq`). -/
noncomputable def histTarget (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (k : 𝓐) (n : ℕ)
    (h : Iic n → 𝓐 × ℝ) : ℝ :=
  T (fun k' ↦ (sumRewards' n h k' + θ₀ k') / ((pullCount' n h k' : ℝ) + 1)) k

/-- **The aRTS design family** (Definition 3.1 of the paper, algorithm form). An algorithm `alg`
is an `α`-throttled aRTS design with offsets `θ₀` and target map `T` if its policy throttles every
over-sampled arm: for any history `h : Iic n → 𝓐 × ℝ`, if arm `k` is over-sampled
(`N_{n+1,k}(h) > (n+1) ρ̂_k(h)`), then the probability the policy assigns to arm `k` for the next
patient is at most `α ρ̂_k(h)`. -/
structure IsARTS (alg : Algorithm 𝓐 ℝ) (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (α : ℝ) : Prop where
  throttle : ∀ (n : ℕ) (h : Iic n → 𝓐 × ℝ) (k : 𝓐),
    ((n : ℝ) + 1) * histTarget θ₀ T k n h < (pullCount' n h k : ℝ) →
      (alg.policy n h {k}).toReal ≤ α * histTarget θ₀ T k n h

end AlphaRAR
end

-- ═══ YDK2026.ARTSRates ═══
section
open MeasureTheory Filter ProbabilityTheory Learning Real Asymptotics
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] [Fintype 𝓐] [StandardBorelSpace 𝓐] [Nonempty 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm 𝓐 ℝ}

/-- **Strong consistency and rates for an aRTS design** (Theorem 4.1 of the paper). Under
Conditions **A** (`hνk`) and **B** (`hT`, `hTpos`, `hT_diff`, and the simplex
conditions `hTnn`, `hTsum`) an `α`-throttled aRTS design satisfies, almost surely for every arm `k`:
the allocation proportion converges to the target `N_{n,k}/n → v_k = T(θ)_k`; the estimator is
consistent `θ̂_{n,k} → θ_k` and achieves the loglog rate `θ̂_{n,k} - θ_k = O(√(log log n / n))`; and
the plug-in target achieves the same rate `ρ̂_{n,k} - v_k = O(√(log log n / n))` — the last two are
the paper's `Θ̂_n - Θ = O(√(log log n / n))` and `n(ρ̂_n - v) = O(√(n log log n))`. Bundles
`aRTS_proportion_tendsto`, `aRTS_theta_consistent`, `aRTS_theta_rate`, `aRTS_rho_rate`. -/
theorem aRTS_LLN (h : IsAlgEnvSeq A Y alg (stationaryEnv ν) P)
    (hνk : ∀ a, MemLp id 2 (ν a)) {θ₀ : 𝓐 → ℝ} {T : (𝓐 → ℝ) → 𝓐 → ℝ} (hT : Continuous T)
    (hTnn : ∀ z k, 0 ≤ T z k) (hTsum : ∀ z, ∑ k, T z k = 1)
    {α : ℝ} (hα : α ∈ Set.Icc (0 : ℝ) 1) (hARTS : IsARTS alg θ₀ T α)
    (hTpos : ∀ z : 𝓐 → ℝ, (∀ k, z k ∈ attainableSet A Y (θ₀ k) k) → ∀ k, 0 < T z k)
    (hT_diff : DifferentiableAt ℝ T ν.means) (k : 𝓐) :
    ∀ᵐ ω ∂P,
      Tendsto (fun n ↦ (pullCount A k n ω : ℝ) / (n : ℝ)) atTop (𝓝 (T ν.means k)) ∧
      Tendsto (fun n ↦ estimator (fun j ↦ actionIndicator A k j ω)
        (Y · ω) (θ₀ k) n) atTop (𝓝 (ν.means k)) ∧
      (fun n ↦ estimator (fun j ↦ actionIndicator A k j ω) (Y · ω) (θ₀ k) n - ν.means k)
          =O[atTop] (fun n ↦ √((n : ℝ) * log (log (n : ℝ))) / (n : ℝ)) ∧
      (fun n ↦ T (fun k' ↦ estimator (fun j ↦ actionIndicator A k' j ω)
        (Y · ω) (θ₀ k') n) k - T ν.means k)
          =O[atTop] (fun n ↦ √((n : ℝ) * log (log (n : ℝ))) / (n : ℝ)) := sorry

end AlphaRAR
end
