import Mathlib.Probability.Process.Filtration
import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Algebra.Order.Star.Real
import Mathlib.Analysis.Asymptotics.SpecificAsymptotics
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Topology.MetricSpace.Pseudo.Lemmas
import Mathlib.Algebra.Ring.IsFormallyReal
import Mathlib.Topology.Separation.CompletelyRegular
import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
import Mathlib.MeasureTheory.Measure.Tight
import Mathlib.MeasureTheory.Order.Group.Lattice
import Mathlib.Probability.Martingale.Centering
import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.Probability.Moments.Variance
import Mathlib.Analysis.PSeries
import Mathlib.Probability.Martingale.Convergence
import Mathlib.Algebra.BigOperators.Module
import Mathlib.Analysis.Normed.Group.Continuity
import Mathlib.Analysis.Normed.Ring.Basic
import Mathlib.Order.Filter.AtTopBot.Archimedean
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Order.CompletePartialOrder
import Mathlib.Probability.Martingale.OptionalStopping
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Probability.Distributions.Gaussian.Fernique
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondJensen
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
import Mathlib.MeasureTheory.Measure.LevyConvergence
import Mathlib.Probability.CondVar
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
import Mathlib.Analysis.Calculus.FDeriv.Basic
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Analysis.SumIntegralComparisons
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.StrongLaw
import Mathlib.Data.Nat.Nth
import Mathlib.Probability.Independence.Basic
import Mathlib.MeasureTheory.Measure.Portmanteau
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.MeasureTheory.Integral.Layercake
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals
import Mathlib.Data.Matrix.ColumnRowPartitioned
import Mathlib.Analysis.Calculus.ContDiff.Comp
import Mathlib.Analysis.Calculus.ContDiff.RCLike
import Mathlib.Analysis.Calculus.LocalExtr.Basic
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Probability.HasCondDistrib
import Mathlib.Probability.HasLaw
import Mathlib.Probability.Martingale.BorelCantelli

/-! # Standalone extraction for `AlphaRAR.aRTSFE_sparse_clt_of_contDiffAt`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee, with the LML declarations the statement rests on vendored in below,
so that this file is self-contained over Mathlib (its transitive imports resolve to Mathlib and
Lean core only, as the Palomar registry requires). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace ProbabilityTheory.Kernel
end ProbabilityTheory.Kernel
namespace AlphaRAR
end AlphaRAR

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Algorithm ═══
-- The declarations of https://github.com/LeanMachineLearning/LML that the statement rests on,
-- copied verbatim (Apache 2.0, Authors: Rémy Degenne, Paulo Rauber) so that this file's imports
-- bottom out in Mathlib. Comparator checks each constant is *identical* to the LML package's.
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1
/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.obs n) := env.isMarkovKernel_obs n
instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) :=
  env.isMarkovKernel_feedback n

section IsAlgEnvSeq

variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StationaryEnv ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- An oblivious environment without observations, in which the distribution of the next feedback
depends only on the last action, but in a possibly time-dependent manner. -/
@[simps]
noncomputable
def obliviousEnv (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment Unit 𝓐 𝓨 where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n := (ν n).prodMkLeft _

/-- A stationary environment without observations, in which the distribution of the next feedback
depends only on the last action. -/
noncomputable
def stationaryEnv (ν : Kernel 𝓐 𝓨) [IsMarkovKernel ν] : Environment Unit 𝓐 𝓨 :=
  obliviousEnv fun _ ↦ ν

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.FiniteActions ═══
section
open MeasureTheory Finset Learning
namespace Learning
variable {𝓞 𝓐 R Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {mR : MeasurableSpace R} {mΩ : MeasurableSpace Ω}
  [DecidableEq 𝓐]
  {alg : Algorithm 𝓞 𝓐 R} {env : Environment 𝓞 𝓐 R}
  {P : Measure Ω} [IsProbabilityMeasure P]
  {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {R' : ℕ → Ω → R}
  {a : 𝓐} {m n t : ℕ} {ω : Ω}

/-- Number of times action `a` was chosen up to time `t` (excluding `t`). -/
noncomputable
def pullCount (A : ℕ → Ω → 𝓐) (a : 𝓐) (t : ℕ) (ω : Ω) : ℕ :=
  #(filter (fun s ↦ A s ω = a) (range t))

/-- Number of pulls of arm `a` in the history before time `n`.
This is the number of entries in `h` in which the arm is `a`. -/
noncomputable
def pullCount' (n : ℕ) (h : Hist 𝓞 𝓐 R n) (a : 𝓐) := #{s | (h s).action = a}

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.SumRewards ═══
section
open MeasureTheory Finset Learning
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}
  [DecidableEq 𝓐] [AddCommGroup 𝓨]
  {P : Measure Ω} [IsProbabilityMeasure P]
  {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {R : ℕ → Ω → 𝓨}
  {a : 𝓐} {m n t : ℕ} {ω : Ω}

/-- Sum of rewards of arm `a` in the history before time `n`. -/
noncomputable
def sumRewards' (n : ℕ) (h : Hist 𝓞 𝓐 𝓨 n) (a : 𝓐) :=
  ∑ s, if (h s).action = a then (h s).feedback else 0

end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.ActionIndicator ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace Learning
variable {Ω 𝓞 𝓐 𝓨 : Type*} {mΩ : MeasurableSpace Ω} {m𝓞 : MeasurableSpace 𝓞}
  {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}
  [MeasurableSingletonClass 𝓐] {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {P : Measure Ω}

/-- The `{0,1}`-valued assignment indicator of action `k`:
`actionIndicator A k n ω = 𝟙{A n ω = k}`. -/
noncomputable def actionIndicator (A : ℕ → Ω → 𝓐) (k : 𝓐) (n : ℕ) (ω : Ω) : ℝ :=
  {ω | A n ω = k}.indicator (fun _ ↦ (1 : ℝ)) ω

end Learning
end

-- ═══ LeanMachineLearning.Means ═══
section
open MeasureTheory ProbabilityTheory Filter Finset
namespace ProbabilityTheory.Kernel
variable {𝓐 𝓨 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} [NormedAddCommGroup 𝓨] [NormedSpace ℝ 𝓨]

/-- The means of a kernel. -/
noncomputable def means (ν : Kernel 𝓐 𝓨) (k : 𝓐) : 𝓨 := (ν k)[id]

end ProbabilityTheory.Kernel
end

-- ═══ YDK2026.Count ═══
section
open Filter Finset MeasureTheory Learning
namespace AlphaRAR

/-- Allocation count of a fixed arm, `N n = ∑_{j<n} X j`, the counts `N_{n,k}` of Section 2 of the
paper. Stated for a general `AddCommMonoid` so it serves both the deterministic per-path counts
(`X : ℕ → ℝ`) and the process-level count (`X : ℕ → Ω → ℝ`, the assignment count process of
`Assignment.lean`). -/
def count {M : Type*} [AddCommMonoid M] (X : ℕ → M) (n : ℕ) : M := ∑ j ∈ range n, X j

end AlphaRAR
end

-- ═══ YDK2026.Deterministic ═══
section
open Finset Filter
open scoped Topology
namespace AlphaRAR
variable (X p ρ : ℕ → ℝ) (α : ℝ)

/-- Sequential estimator of a fixed arm, as in Section 3 of the paper,
`θ̂ n = (∑_{j<n} X j ξ j + θ₀) / (N n + 1)`, with initial value `θ₀` and the `+1`
regularization in the denominator. -/
noncomputable def estimator (ξ : ℕ → ℝ) (θ₀ : ℝ) (n : ℕ) : ℝ :=
  ((∑ j ∈ range n, X j * ξ j) + θ₀) / (count X n + 1)

end AlphaRAR
end

-- ═══ YDK2026.ARTSAlgorithm ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Finset
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {O : ℕ → Ω → Unit} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm Unit 𝓐 ℝ}

/-- History-level plug-in target `ρ̂_k`: the target map `T` applied to the vector of regularized
empirical means `(sumRewards' + θ₀)/(pullCount' + 1)` computed from a history `h : Hist Unit 𝓐 ℝ n`.
This is the design's target as a function of the observed history, matching `aRTSTarget` on the
history of the process (`histTarget_eq`). -/
noncomputable def histTarget (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ) (k : 𝓐) (n : ℕ)
    (h : Hist Unit 𝓐 ℝ n) : ℝ :=
  T (fun k' ↦ (sumRewards' n h k' + θ₀ k') / ((pullCount' n h k' : ℝ) + 1)) k

end AlphaRAR
end

-- ═══ YDK2026.ResponseCLTJoint ═══
section
open MeasureTheory ProbabilityTheory Filter Learning
open scoped Topology
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] [Fintype 𝓐] [DecidableEq 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {O : ℕ → Ω → Unit} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm Unit 𝓐 ℝ}

end AlphaRAR
end

-- ═══ YDK2026.ForcedExploration ═══
section
open MeasureTheory ProbabilityTheory Filter Learning Real
open scoped Topology ENNReal NNReal Matrix
namespace AlphaRAR
variable {Ω 𝓐 : Type*} {mΩ : MeasurableSpace Ω} {m𝓐 : MeasurableSpace 𝓐} [MeasurableSingletonClass 𝓐] {ν : Kernel 𝓐 ℝ} [IsMarkovKernel ν] {P : Measure Ω} [IsProbabilityMeasure P] {O : ℕ → Ω → Unit} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → ℝ} {alg : Algorithm Unit 𝓐 ℝ}

/-- An **exploration schedule**: a nondecreasing threshold `h(m)` with `h(m) → ∞` and
`h(m) = o(m)`. This is the function `h` of Definition 5.1 of the paper with its condition (ii)
weakened. Monotonicity is a harmless convenience that lets `h(ℓ) ≤ h(n)` for `ℓ ≤ n`.

The paper additionally requires `h(m) = o(√m)`; that is `IsSqrtSmall` below, deliberately *not* a
field here, and in fact assumed by *no* result of this development. It would only ever be used by
the `√n`-scaled normality results, and there it is unnecessary
(`underExplored_eventually_empty`: under Condition **B** forced exploration switches itself off,
so any `h(m) = o(m)` does — see `aRTSFE_smallness_op` and `aRTSFE_smallness_upper`). Dropping it is
what makes schedules with `h(m) ≫ √m` available — and those are exactly the ones under which forced
exploration, rather than the data-dependent targeting rule, decides a *sparse* arm's sample size,
which is what earns the sparse componentwise CLT (`pullCount_div_sched_tendsto_one`,
`aRTSFE_sparse_clt`). -/
structure IsExplorationSchedule (hsched : ℕ → ℝ) : Prop where
  /-- The schedule is nondecreasing. -/
  mono : Monotone hsched
  /-- The schedule diverges: `h(m) → ∞` (this is what forces every arm to be sampled infinitely
  often). -/
  tendsto_atTop : Tendsto hsched atTop atTop
  /-- The schedule is `o(m)`. -/
  div_tendsto_zero : Tendsto (fun m ↦ hsched m / (m : ℝ)) atTop (𝓝 0)

/-- **The forced-exploration aRTS design family** (Definition 5.1 of the paper, in algorithm form) —
the `IsARTS` analogue for `aRTSFE`. An algorithm is an `α`-throttled forced-exploration aRTS design
with offsets `θ₀`, target map `T` and schedule `h` when its policy obeys two rules:

* **forced exploration takes priority**: if some arm is under-explored (`N_{n+1,j} ≤ h(n+1)`), then
  all of the policy's mass sits on the *least-sampled* under-explored arms — every other arm gets
  probability zero;
* **outside forced exploration the design is throttled**: an arm that is neither under-sampled nor
  under-explored gets probability at most `α ρ̂_k`.

Compared with `IsARTS`, the throttle carries the extra premise `h(n+1) < N_{n+1,k}`: forced
exploration is allowed to override it, which is exactly what the design is for.

Like `IsARTS`, this is stated purely on histories — no process, measure or filtration appears — so
it is a property of the algorithm alone, checkable design by design. `throttle_of_isARTSFE` and
`fe_of_isARTSFE` transport the two fields to the process-level hypotheses that the asymptotic
theorems consume. -/
structure IsARTSFE [DecidableEq 𝓐] (alg : Algorithm Unit 𝓐 ℝ) (θ₀ : 𝓐 → ℝ) (T : (𝓐 → ℝ) → 𝓐 → ℝ)
    (hsched : ℕ → ℝ) (α : ℝ) : Prop where
  /-- An arm that is neither under-sampled nor under-explored is throttled at `α ρ̂_k`. -/
  throttle : ∀ (n : ℕ) (hist : Hist Unit 𝓐 ℝ n) (k : 𝓐),
    (n : ℝ) * histTarget θ₀ T k n hist < (pullCount' n hist k : ℝ) →
      hsched n < (pullCount' n hist k : ℝ) →
        (alg.policy n (hist, ()) {k}).toReal ≤ α * histTarget θ₀ T k n hist
  /-- When some arm is under-explored, an arm that is not a least-sampled under-explored one cannot
  be drawn. -/
  forced : ∀ (n : ℕ) (hist : Hist Unit 𝓐 ℝ n) (k : 𝓐),
    (∃ j, (pullCount' n hist j : ℝ) ≤ hsched n) →
      (hsched n < (pullCount' n hist k : ℝ) ∨
        ∃ j, (pullCount' n hist j : ℝ) ≤ hsched n ∧
          (pullCount' n hist j : ℝ) < (pullCount' n hist k : ℝ)) →
        alg.policy n (hist, ()) {k} = 0

/-- **The sparse componentwise CLT for `aRTSFE`, with the `FEfed` hypothesis discharged.**
`aRTSFE_sparse_clt` assumes that each sparse arm is eventually fed only by forced exploration;
here that assumption is *proved*, from

* `hstar` — the reversed schedule condition `(⋆) : m log log m = o(h(m)²)`, which replaces the
  paper's `h(m) = o(√m)` and is satisfiable exactly where the paper's condition fails
  (`sched23_star`, `not_isSqrtSmall_sched23`);
* `hT2` — the target is `C²` at `Θ` on the sparse arms. -/
theorem aRTSFE_sparse_clt_of_contDiffAt [Fintype 𝓐] [DecidableEq 𝓐] [StandardBorelSpace 𝓐]
    [Nonempty 𝓐]
    (h : IsAlgEnvSeq O A Y alg (stationaryEnv ν) P) (θ₀ : 𝓐 → ℝ)
    (hνk : ∀ a, MemLp id 2 (ν a))
    {hsched : ℕ → ℝ} (hh : IsExplorationSchedule hsched)
    (hshift : Tendsto
      (fun n ↦ hsched (n - (Fintype.card 𝓐 * ⌈hsched n⌉₊ + 1)) / hsched n) atTop (𝓝 1))
    (hstar : Tendsto (fun m : ℕ ↦ (m : ℝ) * log (log m) / (hsched m * hsched m)) atTop (𝓝 0))
    {T : (𝓐 → ℝ) → 𝓐 → ℝ} (hT : Continuous T) (hTnn : ∀ z a, 0 ≤ T z a)
    (hTsum : ∀ z, ∑ a, T z a = 1)
    {α : ℝ} (hα : α ∈ Set.Icc (0 : ℝ) 1) (hARTSFE : IsARTSFE alg θ₀ T hsched α)
    (hT2 : ∀ a, T ν.means a = 0 → ContDiffAt ℝ 2 (T · a) ν.means) :
    TendstoInDistribution (fun n ω ↦ (WithLp.toLp 2 (fun k ↦
        √(count (actionIndicator A k · ω) n)
          * (estimator (actionIndicator A k · ω) (Y · ω) (θ₀ k) n - ν.means k))
            : EuclideanSpace ℝ 𝓐)) atTop id (fun _ ↦ P)
      (multivariateGaussian 0 (Matrix.diagonal (fun a ↦ Var[id; ν a]))) := sorry

end AlphaRAR
end
